channels:
- conda-forge
dependencies:
- python=3.12.3
- pip<=25.0.1
- pip:
  - mlflow==2.21.3
  - cloudpickle==3.0.0
  - numpy==1.26.4
  - pandas==1.5.3
  - psutil==5.9.0
  - scikit-learn==1.4.2
  - xgboost==1.7.5
name: mlflow-env
